packages:
  # EdgeAuth library
  - "src"
  # Shared packages
  - "packages/*"
  # Cloudflare Workers services
  - "services/*"
  # Frontend applications
  - "apps/*"
  # Exclusions
  - "!**/test/**"
  - "!**/tests/**"
  - "!**/dist/**"
  - "!**/node_modules/**"
# All tooling dependencies are managed in root package.json
# Sub-packages automatically access these via dependency hoisting
# Sub-packages only declare workspace config packages (e.g., @deepracticex/tsup-config)
